# Front matter, Preface, Concerning the Use, Morning Service (blocks 0-119)
REV = {
7: "Although the Books of Common Order, which were prepared for the Reformed Churches, at the beginning, in all countries, contained both prayers and other forms, yet those books were not so much imposed by way of inflexible regulation, as they were offered and accepted as profitable Aids to Worship; and they not only permitted but encouraged the exercise of Free Prayer. In a like spirit the Directory for Worship, adopted at a later time by the Church of Scotland, for the sake of unity with their brethren in the Church of England, so far from establishing an invariable form of Public Worship, expressly provided for a liberty of variation; and it did not in any way prohibit the use of prepared orders and prayers, conformable to the general directions given therein.",
8: "The same wise and blessed liberty is maintained in the Presbyterian Church in the United States of America even to this day. Accordingly it seemed good to the General Assembly of 1903, heeding the desire of many pastors and churches, to appoint a Committee of Ministers and Ruling Elders who should prepare, \"in harmony with the Directory for Worship, a Book of Simple Forms and Services, proper and helpful for voluntary use in Presbyterian churches, in the celebration of the Sacraments, in Marriages and Funerals, and in the Conduct of Public Worship.\" This work has been continued, in faithful obedience, and in humble reliance on the Holy Spirit, through nearly three years of patient labor, and has been submitted, in its progress, to two successive Assemblies. The principles by which the work has been guided were approved, and its completion was ordered. This having been done, so far as God enabled us, in the Book presented here, its publication is now \"Authorized by the General Assembly, for Voluntary Use in the Churches.\"",
9: "This Book of Common Worship is, therefore, not to be taken in any way as a liturgy imposed by authority. Nor is it a substitute for the Directory for Worship, but rather a supplement to it, in which the instructions of the Standards are followed on all essential points, and aid is offered, to those who desire it, for the conduct of the Public Services of Religion with reverence and propriety. We have studied earnestly to embody the truths of our Holy Religion in the language of orderly devotion, to the end that by the Sacraments, the stated Ordinances of the Lord's Day, and all the ordinary and occasional offices of the Church, men may be both instructed and confirmed in the faith of Jesus Christ. We have searched the Holy Scriptures, the usage of the Reformed Churches, and the devotional treasures of early Christianity, for the most noble, clear, and moving expressions of the Spirit of Praise and Prayer; and we have added to these ancient and venerable forms and models such others as might serve, under the guidance of the same Spirit, to give a voice to the present needs, the urgent desires, and the vital hopes of the Church living in these latter days and in the freedom of this Republic.",
29: "¶ *If any church so desires, the Service may begin with the Sentences.*",
35: "¶ *Then the Minister shall say,*",
37: "¶ *Let the People reverently bow down while the Minister leads them in the Invocation, using, if he wishes, one of the following Prayers:*",
39: "ALMIGHTY God, who of Your great mercy have gathered us into Your visible Church; Grant that we may not swerve from the purity of Your worship; but so honor You, both in spirit and in outward form, that Your Name may be glorified in us, and we may be true members of Your only-begotten Son, Jesus Christ our Lord. Amen.",
40: "ETERNAL God, our Maker and our Lord, Giver of all grace, from whom every good prayer comes, and who pour out Your Spirit upon all who seek You; Deliver us, when we draw near to You, from coldness of heart and wanderings of mind; that with steadfast thoughts and pure affections we may worship You in spirit and in truth; through Jesus Christ our Lord. Amen.",
41: "LORD God of heaven and earth, who have made the Church Your dwelling-place, and chosen it as Your rest for ever, and have taught us in Your Word not to forsake the assembling of ourselves together; Regard us in Your mercy, we pray, and send Your Holy Spirit upon us; that our worship may prepare us both to serve You now, and to glorify You hereafter in Your eternal kingdom; through Jesus Christ our Lord. Amen.",
42: "O GOD, who have promised that in all places where You record Your Name, You will meet with Your servants to bless them; Fulfill now Your promise, and make us joyful in Your house of prayer; that our worship, being offered in the Name of Your Son and by the guidance of Your Spirit, may be acceptable to You, and profitable to ourselves; through our only Mediator and Advocate, Jesus Christ our Lord. Amen.",
43: "ALMIGHTY Lord and everlasting God, whom the heaven of heavens cannot contain, much less the temples which our hands have built, but who are ever near to the humble and contrite; Shed down Your Holy Spirit, we pray, on all here assembled; that, being cleansed and illumined by His grace, we may worthily show forth Your praise, meekly learn Your Word, render due thanks for Your mercies, and obtain a gracious answer to our prayers; through the merits of Jesus Christ our Lord. Amen.",
46: "MOST holy and merciful Father; We acknowledge and confess in Your Presence: Our sinful nature prone to evil and slothful in good; And all our shortcomings and offenses against You. You alone know how often we have sinned: In wandering from Your ways; In wasting Your gifts; In forgetting Your love. But You, O Lord, have pity upon us; Who are ashamed and sorry for all in which we have displeased You. Teach us to hate our errors; Cleanse us from our secret faults; And forgive our sins; For the sake of Your dear Son our Savior. And O most holy and loving Father; Send Your purifying grace into our hearts, we pray; That we may from now on live in Your light and walk in Your ways; According to the commandments of Jesus Christ our Lord. Amen.",
49: "ALMIGHTY God, who freely pardons all who repent and turn to Him; Now fulfill in every contrite heart the promise of redeeming grace; remitting all our sins, and cleansing us from an evil conscience; through the perfect sacrifice of Christ our Lord; And keep us evermore in the peace and joy of a holy life; that we may love and serve Him always; In the Name of the Father, the Son, and the Holy Spirit. Amen.",
51: ORIGINAL,   # St. John iii. 16
53: ORIGINAL,   # St. Matthew xi. 28
54: ORIGINAL,   # St. John vi. 37
55: ORIGINAL,   # Scripture benediction
68: "¶ *Before each reading let the Minister say, Hear the Holy Scripture as it is written in such a chapter of such a book: and after the reading, The Lord bless to us the reading of His Holy Word.*",
69: "¶ *If the Old Testament reading is the Ten Commandments, after them the Minister shall read St. Matthew xxii. 37-40, saying before he reads, Hear also the Summary of the Law by our Lord Jesus Christ.*",
76: "¶ *Then the Minister shall say,*",
86: "¶ *In any or all of these Adorations, Thanksgivings, Supplications, and Intercessions, the Minister, if he wishes, may use any of the Prayers given in this Book, under the title of Treasury of Prayers. Or he may carefully order his thoughts and compose his spirit to utter with propriety the desires and petitions of the People, remembering what is suitable and necessary for them in their Common Worship. At the end of the General Prayer the Minister and People shall say together the Lord's Prayer.*",
90: "¶ *The bringing of offerings for the service of God is to be performed as an Act of Worship. Let the Minister, having made such Announcements as are needful and fitting, then say, Let us make our Offering to Almighty God for (naming the cause). If the choir sings a Canticle or Anthem it should be one proper for the occasion.*",
94: "O GOD, most merciful and gracious, of whose bounty we have all received; We ask You to accept this Offering of Your people. Remember in Your love those who have brought it, and those for whom it is given; and so follow it with Your blessing that it may promote peace and good will among men, and advance the kingdom of our Lord and Savior Jesus Christ. Amen.",
101: "¶ *Then the Minister shall say,*",
103: "¶ *Then let the People reverently bow down while the Minister leads them in Prayer, using, if he so desires, one of the following as*",
105: "O GOD, the Protector of all that trust in You, without whom nothing is strong, nothing is holy; Increase and multiply upon us Your mercy, that, You being our ruler and guide, we may so pass through things temporal that we do not finally lose the things eternal. Grant this, O heavenly Father, for Jesus Christ's sake, our Lord. Amen.",
106: "O LORD, the Author of spiritual life, who have given to us the good seed of Your Word; Grant that we may receive it into honest hearts: and so guard it by Your grace from the wiles of Satan and the cares of this life, that the faith and hope and love which You have begotten may be in us the beginning of life eternal; through Jesus Christ our Lord. Amen.",
108: "MOST merciful God, we ask You to grant us that we may earnestly desire, wisely search out, truly perceive, and perfectly fulfill those things which are well pleasing in Your sight, to the praise and glory of Your Name. Amen.",
109: "O GOD, who are the Author of peace and Lover of concord, in knowledge of whom stands our eternal life, whose service is perfect freedom; Defend us, Your humble servants, in all assaults of our enemies; that we, surely trusting in Your defense, may not fear the power of any adversaries; through the might of Jesus Christ our Lord. Amen.",
110: "ALMIGHTY God, who have given us grace at this time with one accord to make our common supplications to You, and who promise that when two or three are gathered together in Your Name You will grant their requests; Fulfill now, O Lord, the desires and petitions of Your servants, as may be most expedient for them; granting us in this world knowledge of Your truth, and in the world to come life everlasting. Amen.",
116: "¶ *After the Benediction it is fitting that the Minister and People remain in silent prayer, asking God that none may leave His House without a blessing.*",
117: "¶ *Note that the last Hymn may be sung after the Prayer if such is the wish and usage of any church.*",
}
